typography_spectrum: 0.8398042405024171
color:
  brandStrength: 0.6251789859961718
  lightness: 0.007317686919122934
  saturation: 0.9525465308688581
  rhythmicContrast: 0.39134352980181575
  brandColors:
    - '#DA7644'
    - '#FFFCFF'
    - '#F4DFCA'
    - '#D29B7B'
    - '#F3C7B2'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/df7c5a96-81d2-45f8-904e-76ac8b5c8121.png
  appId: Luxury Simplified
  type: 'Business Page '
layout_spectrum: 0.24613389582373202
analytics:
  twitter: 'https://twitter.com/LuxSimplified'
author:
  name: 'Chris Leigh-Jones '
  email: chrislj@luxurysimplified.com
  url: 'http://www.luxurysimplified.com/'
name: Luxury Simplified
navigation:
  - name: 'luxurysimplified.com '
    url: 'http://www.luxurysimplified.com/'
    type: external
title: Buy. Sell. Stay. Restore. Build.
description: A vertically integrated luxury real estate firm.
